/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecoagente.mundoBlocos.view;

/**
 *
 * @author rodolfosmac
 */
public class viewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBancada = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBlocos = new javax.swing.JEditorPane();
        cmdAdicionar = new java.awt.Button();
        cmdLimpar = new java.awt.Button();
        paneVisualizador = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVisualizador = new javax.swing.JEditorPane();
        cmdInicial = new javax.swing.JButton();
        cmdObjetivo = new javax.swing.JButton();
        cmdProcessar = new javax.swing.JButton();
        lblEspacos = new java.awt.Label();
        spinEspacos = new javax.swing.JSpinner();
        lblLinhas = new java.awt.Label();
        spinLinhas = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mundo dos Blocos");

        paneBancada.setBorder(javax.swing.BorderFactory.createTitledBorder("Blocos"));

        txtBlocos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBlocos.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtBlocos.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBlocos.setEnabled(false);
        txtBlocos.setFocusable(false);
        txtBlocos.setMargin(new java.awt.Insets(0, 5, 0, 0));
        txtBlocos.setOpaque(false);
        jScrollPane1.setViewportView(txtBlocos);

        cmdAdicionar.setLabel("adicionar");
        cmdAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdicionarActionPerformed(evt);
            }
        });

        cmdLimpar.setLabel("limpar");

        javax.swing.GroupLayout paneBancadaLayout = new javax.swing.GroupLayout(paneBancada);
        paneBancada.setLayout(paneBancadaLayout);
        paneBancadaLayout.setHorizontalGroup(
            paneBancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(paneBancadaLayout.createSequentialGroup()
                .addGap(0, 118, Short.MAX_VALUE)
                .addComponent(cmdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        paneBancadaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdAdicionar, cmdLimpar});

        paneBancadaLayout.setVerticalGroup(
            paneBancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBancadaLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(2, 2, 2)
                .addGroup(paneBancadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        paneBancadaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmdAdicionar, cmdLimpar});

        paneVisualizador.setBorder(javax.swing.BorderFactory.createTitledBorder("Bancada"));

        txtVisualizador.setBorder(null);
        txtVisualizador.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtVisualizador.setEnabled(false);
        txtVisualizador.setFocusable(false);
        txtVisualizador.setMargin(new java.awt.Insets(0, 2, 0, 0));
        jScrollPane2.setViewportView(txtVisualizador);

        cmdInicial.setText("Inicial");
        cmdInicial.setToolTipText("");

        cmdObjetivo.setText("Objetivo");

        cmdProcessar.setText("Processar");
        cmdProcessar.setToolTipText("");

        lblEspacos.setText("Colunas:");

        lblLinhas.setText("Linhas:");

        javax.swing.GroupLayout paneVisualizadorLayout = new javax.swing.GroupLayout(paneVisualizador);
        paneVisualizador.setLayout(paneVisualizadorLayout);
        paneVisualizadorLayout.setHorizontalGroup(
            paneVisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(paneVisualizadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(spinLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblEspacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(spinEspacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(cmdInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdObjetivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdProcessar))
        );
        paneVisualizadorLayout.setVerticalGroup(
            paneVisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneVisualizadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneVisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEspacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinEspacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdInicial)
                    .addComponent(cmdObjetivo)
                    .addComponent(cmdProcessar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBancada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneVisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneVisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneBancada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdicionarActionPerformed
        // TODO add your handling code here:
        StringBuilder strBlocos = new StringBuilder("");
        strBlocos.append("----------------------------------------------");
        strBlocos.append(" Alias     Descricao       Posicao  Objetivo  ");
        strBlocos.append("----------------------------------------------");
        
        txtBlocos.setText(strBlocos.toString());
    }//GEN-LAST:event_cmdAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MacOS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cmdAdicionar;
    private javax.swing.JButton cmdInicial;
    private java.awt.Button cmdLimpar;
    private javax.swing.JButton cmdObjetivo;
    private javax.swing.JButton cmdProcessar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label lblEspacos;
    private java.awt.Label lblLinhas;
    private javax.swing.JPanel paneBancada;
    private javax.swing.JPanel paneVisualizador;
    private javax.swing.JSpinner spinEspacos;
    private javax.swing.JSpinner spinLinhas;
    private javax.swing.JEditorPane txtBlocos;
    private javax.swing.JEditorPane txtVisualizador;
    // End of variables declaration//GEN-END:variables
}
